# Generated by Django 5.2.1 on 2025-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingcode',
            name='telegram_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
