# Generated by Django 5.2 on 2025-04-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='candidate',
            name='surname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
