# Generated by Django 5.2.1 on 2025-06-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images/'),
        ),
    ]
