# Generated by Django 5.2.1 on 2025-06-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
